Add integration test for Parser
membraneframework/membrane_h264_ffmpeg_plugin pull request #57
Opened 2022-05-13 05:48 UTC by Rados13

2022-05-13 06:32 UTC, daniel-jodlos requested changes

2022-05-13 06:32 UTC, daniel-jodlos commented on lib/membrane_h264_ffmpeg/parser.ex
> +      Membrane.Logger.warn("Flag skip_until_parameters? is not compatible with H264.RemoteStream")
I think we should be a little more verbose about the action that we are taking.
```suggestion
      Membrane.Logger.warn("""
      Flag skip_until_parameters? is not compatible with Membrane.H264.RemoteStream caps.
      It is being automatically disabled.
      """)
```

2022-05-13 06:32 UTC, daniel-jodlos commented on test/parser/parser_integration_test.exs
> +  defp chunk_bits(binary, n) do
https://hexdocs.pm/bunch/Bunch.Binary.html#chunk_every/2

2022-05-13 06:32 UTC, daniel-jodlos commented on test/parser/parser_integration_test.exs
> +  @stream_with_params File.read!("test/fixtures/input-10-720p.h264")
I think we should be feeding the stream without the parameters in order to actually test anything

2022-05-13 06:32 UTC, daniel-jodlos commented on test/parser/parser_integration_test.exs
> +  defp create_pipeline(input_file, output_file) do
I don't think you're using `input_file` parameter

2022-05-24 06:32 UTC, Rados13 commented
Solved in #60

2022-05-24 06:32 UTC, closed without merging