Migrate to Core v0.11
membraneframework/membrane_h264_ffmpeg_plugin pull request #73
Opened 2022-11-21 12:49 UTC by LVala

I have one doubt, when changing `{{:error, reason}, state}` to `raise ...` I used `raise "Error: #{inspect(reason)}"` everywhere and I'm wondering whether that's enough or should I make the error messages more verbose.

2022-11-21 16:12 UTC, bblaszkow06 requested changes

2022-11-21 16:12 UTC, bblaszkow06 commented on lib/membrane_h264_ffmpeg/parser.ex
> +        raise("Cannot send Membrane.H264.RemoteStream stream_format after the stream has started")
In addition to reformatting, I'd rephrase the error a bit:
```suggestion
    raise "Cannot handle Membrane.H264.RemoteStream format after the stream has started"
  end
```

2022-11-25 09:52 UTC, varsill commented
@LVala @bblaszkow06  Would it be possible to update the dependency to membrane_h264_format to 0.4.0?

2022-11-25 12:24 UTC, bblaszkow06 commented on mix.exs
>        {:membrane_h264_format, "~> 0.3.0"},
As requested, pls update the format package
```suggestion
      {:membrane_h264_format, "~> 0.4.0"},

```

2022-11-25 14:56 UTC, LVala commented
Because of the new line `{:ok, :unknown} -> raise "Unknown H264 profile!"` in `get_profile!` function, some tests do not pass, that will be investigated.

2022-11-29 12:37 UTC, FelonEkonom commented
@LVala this new line also causes errors in RTP Plugin tests

2022-11-29 16:43 UTC, bblaszkow06 approved these changes

2022-11-30 12:42 UTC, merged